apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: ng  # Specify the namespace
  labels:
    app: nodejs-app
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: nithingganesh/nithin-nodejs-app:latest 
        imagePullPolicy: Always  # Always pull the latest image
        ports:
        - containerPort: 3000 
